### ISSUE TITLE
The mod Prepare Carefully does not open with the Adrenaline mod

### ISSUE THREAD

**Issue by Taranchuk** [XeoNovaDan/Adrenaline#2]
Today I found that I could not open the character ediror from the mod. It shows me instead a window with the text of the error "Prepare Carefully failed to initialize". Then I started throwing out the mods from the modlist and found that your mod seems to be the reason for not launching the character editor. At least, when I deactivated the Adrenaline mod, the Prepare Carefully window opened normally, and when I activated the mod, the window did not open again.

**Comment by XeoNovaDan** [comment]
Thanks for pointing this out! Found the source of the issue and will work on that; it's because HediffGiver_Adrenaline doesn't actually have any HediffDef assigned to the ``hediff`` field since that's all handed through a DefModExtension, and EdB Prepare Carefully references that field when generating 'InjuryOptions' (seems to be related to generating injuries).

Just about to push an update which fixes this - it should be up within 10 minutes from when I posted this

**Comment by XeoNovaDan** [comment]
And done! Closing this issue now.

Link for convenience: https://github.com/XeoNovaDan/Adrenaline/releases/tag/v0.9
